// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ReadBetter",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "ReadBetter",
            targets: ["AppModule"],
            bundleIdentifier: "com.ReadBetter.ReadBetter",
            teamIdentifier: "U9SF34QD7R",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ReadBetter uses the camera to scan text from books so you can practice words with OCR."),
                .microphone(purposeString: "ReadBetter uses the microphone to help you practice pronunciation."),
                .speechRecognition(purposeString: "ReadBetter uses speech recognition to check your pronunciation accuracy.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            sources: ["App/ContentView.swift", "App/MyApp.swift", "App/Utilities", "Engine", "Managers", "Models", "Views"],
            resources: [
                .process("App/Assets.xcassets"),
                .process("App/Resources")
            ],
            exclude: ["App/Assets.xcassets"]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)